import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'package:power_pulse/data/models/trainer_models.dart';
import 'package:power_pulse/data/repositories/trainer_repository.dart';
import 'package:power_pulse/data/repositories/trainee_repository.dart';
import 'package:power_pulse/services/drive_service.dart';
import 'package:power_pulse/models/trainer_registration_data.dart';
import 'package:power_pulse/utils/error_handler.dart';
import 'dart:io';

class TrainerProvider extends ChangeNotifier {
  final TrainerRepository _trainerRepository = TrainerRepository();
  final TraineeRepository _traineeRepository = TraineeRepository();
  Trainer? _currentTrainer;
  TrainerStats? _stats;
  List<Trainer> _trainers = [];
  List<TrainingPlan> _currentTrainerPlans = [];
  List<Map<String, dynamic>> _subscriptions = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<Trainer> get trainers => _trainers;
  List<TrainingPlan> get currentTrainerPlans => _currentTrainerPlans;
  List<Map<String, dynamic>> get subscriptions => _subscriptions;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  Trainer? get currentTrainer => _currentTrainer;
  TrainerStats? get stats => _stats;

  Future<void> fetchTrainerSubscriptions(int trainerId) async {
    try {
      _subscriptions = await _trainerRepository.getTrainerSubscriptions(
        trainerId,
      );
      notifyListeners();
    } catch (e) {
      debugPrint('Error fetching trainer subscriptions: $e');
    }
  }

  Future<void> fetchTrainerStats(int trainerId) async {
    try {
      _stats = await _trainerRepository.getTrainerStats(trainerId);

      // If the stats endpoint returned default zeros (e.g. 404 fallback),
      // try to compute from the subscriptions endpoint instead.
      if ((_stats?.totalAmount ?? 0) == 0) {
        await _computeStatsFromSubscriptions(trainerId);
      }

      notifyListeners();
    } catch (e) {
      debugPrint('Error fetching trainer stats: $e');
    }
  }

  /// Fallback: fetch subscriptions for this trainer and sum up plan prices.
  Future<void> _computeStatsFromSubscriptions(int trainerId) async {
    try {
      final response = await _trainerRepository.getTrainerSubscriptions(
        trainerId,
      );
      if (response.isNotEmpty) {
        double totalAmount = 0.0;
        final today = DateTime.now();
        final todayStart = DateTime(today.year, today.month, today.day);
        double todayAmount = 0.0;

        for (final sub in response) {
          final rawPrice =
              sub['priceSnapshot'] ??
              sub['PriceSnapshot'] ??
              sub['planPrice'] ??
              sub['PlanPrice'] ??
              sub['price'] ??
              sub['Price'];

          double parsedPrice = 0.0;
          if (rawPrice is num) {
            parsedPrice = rawPrice.toDouble();
          } else if (rawPrice is String) {
            parsedPrice = double.tryParse(rawPrice) ?? 0.0;
          }
          totalAmount += parsedPrice;

          final startRaw = sub['startDate'] ?? sub['StartDate'];
          if (startRaw is String) {
            final start = DateTime.tryParse(startRaw);
            if (start != null) {
              final startDay = DateTime(start.year, start.month, start.day);
              if (startDay == todayStart) {
                todayAmount += parsedPrice;
              }
            }
          }
        }

        _stats = TrainerStats(
          totalClients: response.length,
          todayAmount: todayAmount,
          totalAmount: totalAmount,
        );
      }
    } catch (e) {
      debugPrint('Error computing stats from subscriptions: $e');
    }
  }

  Future<void> fetchTrainers() async {
    if (_isLoading && _trainers.isNotEmpty) return;

    _isLoading = true;
    _errorMessage = null;
    Future.microtask(() => notifyListeners());

    try {
      final fetchedTrainers = await _trainerRepository.getTrainers();
      // Filter out test trainers generated by the backend testing scripts
      _trainers = fetchedTrainers
          .where(
            (t) =>
                !t.name.toLowerCase().contains('test ai trainer') &&
                !t.name.toLowerCase().startsWith('test'),
          )
          .toList();
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _isLoading = false;
      if (e is DioException) {
        _errorMessage =
            'Failed to load trainers. The server might be down or unreachable.';
      } else {
        _errorMessage = 'An unexpected error occurred while loading trainers.';
      }
      notifyListeners();
    }
  }

  Future<void> fetchCurrentTrainer(int id) async {
    _isLoading = true;
    _errorMessage = null;
    Future.microtask(() => notifyListeners());

    try {
      _currentTrainer = await _trainerRepository.getTrainerDetails(id);
      _currentTrainerPlans = await _trainerRepository.getPlans(id);
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
    }
  }

  Future<void> fetchTrainerPlans(int trainerId) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _currentTrainerPlans = await _trainerRepository.getPlans(trainerId);
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
    }
  }

  Future<bool> createPlan(int trainerId, Map<String, dynamic> planData) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.createPlan(trainerId, planData);
      await fetchTrainerPlans(trainerId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<bool> saveDailyNote(
    int trainerId,
    int traineeId,
    String noteTitle,
    String noteContent,
  ) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      // 1. Fetch active subscriptions for trainer
      final subscriptions = await _trainerRepository.getTrainerSubscriptions(
        trainerId,
      );

      // 2. Find ALL subscriptions for this trainee
      final traineeSubs = subscriptions
          .where((s) => s['traineeId'] == traineeId)
          .toList();
      if (traineeSubs.isEmpty) {
        _errorMessage = 'No active subscription found for this trainee.';
        _isLoading = false;
        notifyListeners();
        return false;
      }

      // Sort descending by ID to ensure we target the *newest* subscription!
      traineeSubs.sort((a, b) => (b['id'] as int).compareTo(a['id'] as int));
      final sub = traineeSubs.first;

      if (sub.isEmpty || sub['id'] == null) {
        _errorMessage = 'No active subscription found for this trainee.';
        _isLoading = false;
        notifyListeners();
        return false;
      }

      final subscriptionId = sub['id'] as int;

      // 3. Save the note
      final response = await _trainerRepository.addDailyNote(
        subscriptionId,
        noteTitle,
        noteContent,
      );

      _isLoading = false;
      notifyListeners();
      return response != null;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<List<Map<String, dynamic>>> fetchNotesForTrainee(
    int trainerId,
    int traineeId,
  ) async {
    try {
      final subscriptions = await _trainerRepository.getTrainerSubscriptions(
        trainerId,
      );
      final traineeSubs = subscriptions
          .where((s) => s['traineeId'] == traineeId)
          .toList();
      if (traineeSubs.isEmpty) return [];

      // Sort descending by ID to ensure we fetch notes for the *newest* subscription!
      traineeSubs.sort((a, b) => (b['id'] as int).compareTo(a['id'] as int));
      final sub = traineeSubs.first;
      if (sub.isEmpty || sub['id'] == null) return [];

      final subId = sub['id'] as int;
      final subDetails = await _trainerRepository.getSubscriptionDetails(subId);

      if (subDetails != null) {
        // Try 'dailyNotes' first
        if (subDetails['dailyNotes'] != null) {
          return List<Map<String, dynamic>>.from(subDetails['dailyNotes']);
        }
        // Fallback to 'notes'
        if (subDetails['notes'] != null) {
          return List<Map<String, dynamic>>.from(subDetails['notes']);
        }
      }

      // Explicit REST fallback if the notes weren't eager-loaded
      try {
        final explicitNotes = await _trainerRepository.getDailyNotes(subId);
        if (explicitNotes != null) {
          return explicitNotes;
        }
      } catch (e) {
        debugPrint('Explicit notes endpoint fallback failed: $e');
      }
    } catch (e) {
      debugPrint('Error fetching notes: $e');
    }
    return [];
  }

  Future<bool> updatePlan(
    int trainerId,
    int planId,
    Map<String, dynamic> planData,
  ) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.updatePlan(trainerId, planId, planData);
      await fetchTrainerPlans(trainerId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<bool> deletePlan(int trainerId, int planId) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.deletePlan(trainerId, planId);
      await fetchTrainerPlans(trainerId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<bool> subscribeToPlan(int traineeId, int trainingPlanId) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _traineeRepository.subscribe(traineeId, trainingPlanId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<Trainer?> getTrainerDetails(int id) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final trainer = await _trainerRepository.getTrainerDetails(id);
      _isLoading = false;
      notifyListeners();
      return trainer;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return null;
    }
  }

  Future<bool> addWorkout(
    int trainerId,
    Map<String, dynamic> workoutData,
  ) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.addWorkout(trainerId, workoutData);
      // Refresh trainer details so new workout appears in the library
      await fetchCurrentTrainer(trainerId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<int?> addWorkoutForId(
    int trainerId,
    Map<String, dynamic> workoutData,
  ) async {
    try {
      final newWorkoutId = await _trainerRepository.addWorkoutForId(
        trainerId,
        workoutData,
      );
      return newWorkoutId;
    } catch (e) {
      return null;
    }
  }

  Future<bool> addCertificate(
    int trainerId,
    Map<String, dynamic> certificateData,
  ) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.addCertificate(trainerId, certificateData);
      // Refresh details?
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<bool> updateProfile(int trainerId, Map<String, dynamic> data) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final driveService = DriveService();
      Map<String, dynamic> requestData = {};

      if (_currentTrainer != null) {
        requestData = _currentTrainer!.toJson();
      }

      // 1. Merge incoming updates
      requestData.addAll(data);

      // 2. Handle Bio/About mapping
      if (data.containsKey('about')) {
        requestData['bio'] = data['about'];
        requestData.remove('about');
      }

      // 3. Handle Specializations (Names/Maps to IDs)
      final rawSpecs = requestData['specializations'];
      if (rawSpecs is List) {
        final specializationMap = {
          'Weight Loss': 1,
          'Strength Training': 2,
          'Bodybuilding': 3,
          'Rehabilitation': 4,
          'Senior Fitness': 5,
          'Yoga': 6,
          'Athletic Performance': 7,
        };

        final List<int> specIds = rawSpecs
            .map((e) {
              if (e is String) return specializationMap[e];
              if (e is Specialization) {
                return e.id != 0 ? e.id : specializationMap[e.name];
              }
              if (e is Map) {
                final id = e['id'];
                if (id != null && id != 0) return id as int;
                return specializationMap[e['name']];
              }
              return null;
            })
            .where((id) => id != null)
            .cast<int>()
            .toList();

        requestData['specializationIds'] = specIds;
      }

      // 4. Handle Certifications (Upload images and build data for separate API calls)
      final rawCerts =
          requestData['certifications'] ?? requestData['certificates'];
      final List<Map<String, dynamic>> certificatesList = [];

      if (rawCerts is List) {
        for (var certData in rawCerts) {
          int? certId;
          String name = '';
          String organization = '';
          String yearStr = '0';
          String? imageUrl;
          File? imageFile;

          if (certData is TrainerCertification) {
            certId = certData.id;
            name = certData.name;
            organization = certData.organization;
            yearStr = certData.year;
            imageUrl = certData.imageUrl;
            imageFile = certData.image;
          } else if (certData is Certificate) {
            certId = certData.id;
            name = certData.name;
            organization = certData.organization;
            yearStr = certData.year.toString();
            imageUrl = certData.imageUrl;
          } else if (certData is Map<String, dynamic>) {
            certId = certData['id'];
            name = certData['certName'] ?? certData['name'] ?? '';
            organization = certData['issuer'] ?? certData['organization'] ?? '';
            yearStr = (certData['year'] ?? 0).toString();
            imageUrl = certData['imageUrl'];
          }

          if (imageFile != null) {
            imageUrl = await driveService.uploadFile(file: imageFile);
          }

          certificatesList.add({
            'id': certId,
            'certName': name,
            'issuer': organization,
            'year': int.tryParse(yearStr) ?? 0,
            'imageUrl': imageUrl,
            '_hasNewImage': imageFile != null, // Track if image was changed
          });
        }
      }

      // 5. Final Cleanup (Removing read-only or redundant fields)
      requestData.remove('id');
      requestData.remove('email');
      requestData.remove('rating');
      requestData.remove('workouts');
      requestData.remove('plans');
      requestData.remove('specializations');
      requestData.remove('certifications');
      requestData.remove('certificates'); // Handled below via DELETE+POST

      debugPrint('Sending Final Payload to Backend: $requestData');
      await _trainerRepository.updateProfile(trainerId, requestData);

      // 6. Sync certificates: handle deletes, updates, and adds
      //    The backend only supports POST (create) and DELETE for certs.
      //    No PUT endpoint exists for updating individual certs.

      // 6a. Find certs that were REMOVED by the user (exist on backend but not in submitted list)
      final submittedCertIds = certificatesList
          .map((c) => c['id'])
          .where((id) => id != null && id != 0)
          .toSet();
      final existingCerts = _currentTrainer?.certificates ?? [];

      for (final existingCert in existingCerts) {
        if (!submittedCertIds.contains(existingCert.id)) {
          // This cert was removed by the user → DELETE it
          try {
            debugPrint('Deleting removed certificate ${existingCert.id}...');
            await _trainerRepository.deleteCertificate(
              trainerId,
              existingCert.id,
            );
            debugPrint('Certificate ${existingCert.id} deleted');
          } catch (e) {
            debugPrint('Failed to delete cert ${existingCert.id}: $e');
          }
        }
      }

      // 6b. Handle modified and new certs
      for (final certData in certificatesList) {
        final certId = certData['id'];
        final certPayload = Map<String, dynamic>.from(certData);
        certPayload.remove('id');
        final hasNewImage = certData['_hasNewImage'] == true;
        certPayload.remove('_hasNewImage');

        if (certId != null && certId != 0) {
          if (!hasNewImage) {
            // Cert was not changed, skip it
            debugPrint('Certificate $certId unchanged, skipping');
            continue;
          }
          // Existing cert was modified → DELETE old, POST replacement
          try {
            debugPrint('Deleting old certificate $certId for replacement...');
            await _trainerRepository.deleteCertificate(
              trainerId,
              certId is int ? certId : int.parse(certId.toString()),
            );
            debugPrint('Old certificate $certId deleted');
          } catch (e) {
            debugPrint('Failed to delete cert $certId: $e');
            continue; // Don't create duplicate
          }
        }

        // POST new/replacement cert
        try {
          debugPrint('Creating certificate: ${certPayload['certName']}');
          await _trainerRepository.addCertificate(trainerId, certPayload);
          debugPrint('Certificate created successfully');
        } catch (e) {
          debugPrint('Failed to create cert: $e');
        }
      }

      // Refresh details
      await fetchCurrentTrainer(trainerId);

      _isLoading = false;
      notifyListeners();
      return true;
    } on DioException catch (e) {
      debugPrint('Profile Update Error Response: ${e.response?.data}');
      debugPrint('Profile Update Error: $e');
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    } catch (e) {
      debugPrint('Profile Update Error: $e');
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }

  Future<bool> updateProfileImage(int trainerId, String imageUrl) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _trainerRepository.updateProfileImage(trainerId, imageUrl);
      await fetchCurrentTrainer(trainerId);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      _errorMessage = ErrorHandler.getUserFriendlyMessage(e);
      notifyListeners();
      return false;
    }
  }
}
