// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnJDOKxRjdkJSgKO7m6pk8feqD7ccxuEs',
    appId: '1:1084346385742:ios:9d3d0f41ae194dae920a1f',
    messagingSenderId: '1084346385742',
    projectId: 'power-pulse-fa36d',
    storageBucket: 'power-pulse-fa36d.firebasestorage.app',
    iosBundleId: 'com.example.powerPulse',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGs0SF4kRMmxe3tzF9l1JjkKblxkSvKzk',
    appId: '1:1084346385742:android:3503297936b18ae3920a1f',
    messagingSenderId: '1084346385742',
    projectId: 'power-pulse-fa36d',
    storageBucket: 'power-pulse-fa36d.firebasestorage.app',
  );
}
